fos_rest:
  disable_csrf_role: ROLE_USER
  param_fetcher_listener: true
  body_listener: true
  format_listener: true
  format_listener:
      enabled: true
      rules:
          fallback_format: json
          exception_fallback_format: json
  access_denied_listener:
      json: true
  allowed_methods_listener: true
  routing_loader:
      default_format: json
      include_format: false
  view:
      default_engine: json
      view_response_listener: 'force'
      formats:
          json : true
      templating_formats:
          html: true
  exception:
      codes:
          'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
          'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
      messages:
          'Symfony\Component\Routing\Exception\ResourceNotFoundException': true

nelmio_api_doc:
    sandbox:
        request_format:
            method: accept_header

nelmio_cors:
    paths:
        '^/':
            allow_origin: ['*']
            allow_headers: ['Authorization', 'X-Requested-With', 'Content-Type', 'Accept', 'Origin', 'X-Custom-Auth']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
            max_age: 3600
