todo:
    resource: "@TodoBundle/Controller/"
    type:     annotation
    prefix:   /todo

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /doc
        permanent: true

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /doc
    defaults:  { _format: json }
